Fix pager in admin
BoltAuth/Auth pull request #50
Opened 2018-12-11 06:01 UTC by ncareau

Fixes #34

2018-12-11 17:13 UTC, jadwigo requested changes
Ni @ncareau ... this is a great start.
But if you change the line with the include https://github.com/BoltAuth/Auth/pull/50/commits/23b8975ec6b997ea565ddd52b75a58d553395af3#diff-4329ff51e5224f4efcff26c6866eb9bcL112 to the following way the extension will still keep using the default bolt pager include: 

```twig
            {% include '@bolt/components/pager.twig' with {'pager': pager.pager} %}
```

2018-12-12 01:26 UTC, ncareau commented
Changed the include path as asked.

2018-12-12 08:51 UTC, jadwigo approved these changes

2018-12-12 08:52 UTC, jadwigo commented
This change works for me and fixes #34, @SahAssar can you merge this in to a new release?

2020-08-06 08:00 UTC, merged